version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        restart: "no"
        environment:
            - PYTHONPATH=/opt/myapp/current/src/main/:/opt/myapp/current/src/test/
        volumes:
            - ".:/opt/myapp/current"

