version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        restart: "no"
        environment:
            - PYTHONPATH=src/main/python
        volumes:
            - "./VERSION:/app/VERSION"
            - "./requirements.txt:/app/requirements.txt:ro"
            - "./src:/app/src:ro"
            - "./tasks.py:/app/tasks.py:ro"
            - "./tasks:/app/tasks:ro"
            - "./htmlcov:/app/htmlcov"

