version: "3"
services:
    mysql:
        image: mysql:5.7
        restart: "always"
        environment:
            - MYSQL_ROOT_PASSWORD=
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=myapp
            - MYSQL_USER=myapp
            - MYSQL_PASSWORD=password
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        restart: "no"
        environment:
            - PYTHONPATH=/opt/myapp/current/src/main/:/opt/myapp/current/src/test/:/opt/myapp/current/src/tasks/
            - PYTHONPYCACHEPREFIX=/opt/myapp/current/target/cache/__pycache__/
        links:
            - mysql:db
        volumes:
            - ".:/opt/myapp/current"

