version: "3"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        restart: "no"
        environment:
            - PYTHONPATH=/app/src/main/python/:/app/src/test/python/
        volumes:
            - "./app:/app"

